"""
Protocol constants for PSI.
"""

PROTOCOL_VERSION = "1.0"
SECURITY_LEVEL = 128  # bits
CURVE_NAME = "secp256r1"
HASH_ALGORITHM = "SHA-256"
HASH_OUTPUT_SIZE = 32  # bytes
POINT_SERIALIZED_SIZE = 33  # bytes compressed
MESSAGE_TIMEOUT_MS = 30000
MAX_CONTACT_LIST_SIZE = 1000000
MIN_CONTACT_LENGTH = 1
MAX_CONTACT_LENGTH = 256
